language: java
sudo: false

matrix:
  fast_finish: true
  include:

    # verify: Errorprone, JaCoCo, FindBugs, Checkstyle
    - jdk: oraclejdk8
      env: DESC="mvn_clean_compile_verify"
      script: "mvn clean compile verify"

branches:
  only:
    - master