language: java
sudo: false

matrix:
  fast_finish: true
  include:

    # verify
    - jdk: oraclejdk8
      env: DESC="mvn_clean_verify"
      script: "mvn clean verify"

branches:
  only:
    - master